### PR TITLE
Updated UI, authentication, deploy progress

### PR DESCRIPTION
**Pull request by TrueshotBarrage**
- Fast-forward to new, updated UI developed by Justin
- NextAuth used for authentication protocol

### CODE REVIEW

**Comment by TrueshotBarrage** [comment]
I fixed up a bunch of rebase issues, so take a quick look at this PR. Once we review, approve and merge, we will need to "start clean" with our existing branches.

**Review by justinkang01 — CHANGES_REQUESTED** [review]
The /api/secret/ directory is deprecated; no longer a useful directory/file.
Everything else looks good.

**Comment by TrueshotBarrage** [comment]
> The /api/secret/ directory is deprecated; no longer a useful directory/file.
> Everything else looks good.

That's fine, but can you squash the commit into the previous one? Just rollback the commit with: `git reset --hard HEAD^1` and remove the folder again, then `git commit --amend`

**Comment by TrueshotBarrage** [comment]
```shell
[03/29/21 17:31:53] /Users/trueshot/Documents/GitHub/scheduler git:(TrueshotBarrage/oauth)➜ git status       
On branch TrueshotBarrage/oauth
Your branch is behind 'origin/TrueshotBarrage/oauth' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean

[03/29/21 17:32:00] /Users/trueshot/Documents/GitHub/scheduler git:(TrueshotBarrage/oauth)➜ git push --force
Total 0 (delta 0), reused 0 (delta 0)
To github.com:TrueshotBarrage/thymekeep.git
 + 82fbe90...9007737 TrueshotBarrage/oauth -> TrueshotBarrage/oauth (forced update)

[03/29/21 17:32:48] /Users/trueshot/Documents/GitHub/scheduler git:(TrueshotBarrage/oauth)➜ ls pages/api 
auth         examples     googleapi.js secret

[03/29/21 17:32:57] /Users/trueshot/Documents/GitHub/scheduler git:(TrueshotBarrage/oauth)➜ rm -rf pages/api/secret

[03/29/21 17:33:07] /Users/trueshot/Documents/GitHub/scheduler git:(TrueshotBarrage/oauth*)➜ git status
On branch TrueshotBarrage/oauth
Your branch is up to date with 'origin/TrueshotBarrage/oauth'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    pages/api/secret/index.js

no changes added to commit (use "git add" and/or "git commit -a")

[03/29/21 17:33:10] /Users/trueshot/Documents/GitHub/scheduler git:(TrueshotBarrage/oauth*)➜ git add pages && git commit --amend
[TrueshotBarrage/oauth 1dbea22] Updated UI & Implemented NextAuth authentication
 Date: Sat Mar 27 23:58:10 2021 -0400
 18 files changed, 392 insertions(+), 242 deletions(-)
 create mode 100644 components/activeLink.js
 create mode 100644 components/activeLink.module.css
 create mode 100644 components/calendar.js
 create mode 100644 components/calendar.module.css
 rewrite components/layout.js (78%)
 rewrite components/layout.module.css (78%)
 rewrite components/profileLayout.js (81%)
 delete mode 100644 pages/api/test.js
 rewrite pages/index.js (99%)
 create mode 100644 pages/profile/default.png

[03/29/21 17:33:42] /Users/trueshot/Documents/GitHub/scheduler git:(TrueshotBarrage/oauth)➜ git status
On branch TrueshotBarrage/oauth
Your branch and 'origin/TrueshotBarrage/oauth' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

[03/29/21 17:33:50] /Users/trueshot/Documents/GitHub/scheduler git:(TrueshotBarrage/oauth)➜ git push --force
Enumerating objects: 41, done.
Counting objects: 100% (41/41), done.
Delta compression using up to 8 threads
Compressing objects: 100% (24/24), done.
Writing objects: 100% (24/24), 17.90 KiB | 8.95 MiB/s, done.
Total 24 (delta 9), reused 7 (delta 0)
remote: Resolving deltas: 100% (9/9), completed with 8 local objects.
To github.com:TrueshotBarrage/thymekeep.git
 + 9007737...1dbea22 TrueshotBarrage/oauth -> TrueshotBarrage/oauth (forced update)
```

**Comment by TrueshotBarrage** [comment]
This is what I meant, does this make sense? If not I can hop on a quick call and explain what I did here.

**Pull request merged**
